---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by luxizhu.
--- DateTime: 2021/3/16 10:43
---
--- accepts a table of values to dump
--- empty table default as object
--- example：
--- local yaml_dump = require("yaml-dump")
--- yaml_dump.as_array(lua_table.aaa)
--- print( yaml_dump(lua_table) )
---

local string = string
local setmetatable = setmetatable
local getmetatable = getmetatable
local table = table
local ipairs = ipairs
local pairs = pairs

local space = "\x20\x20"
local indent_ = {
    [0] = "",
    [1] = space,
    [2] = string.rep(space, 2),
    [3] = string.rep(space, 3),
    [4] = string.rep(space, 4),
    [5] = string.rep(space, 5),
}

local function is_std_key(key)
    return key == string.match(key, "^[%w%-_]+")
end

local _M = {
    version = "yaml-dump-1.0.0",
    array_mt = {},
}
setmetatable(indent_, {
    __index = function(t, idx)
        local value = string.rep(space, idx)
        t[idx] = value
        return value
    end })

function _M.as_array(t)
    if #t == 0 then
        setmetatable(t, _M.array_mt)
    end
    return t
end

local function yaml_dump(t, deps)
    --- when table empty, json_like = true, key:value不换行
    local lines, json_like = {}
    if #t > 0 then
        for _, value in ipairs(t) do
            local typ = type(value)
            if typ == "table" then
                value, json_like = yaml_dump(value, deps + 1)
                if not json_like then
                    value = "\n" .. value
                end
            elseif typ == "string" then
                value = string.format("%q", value)
            else
                value = string.format("%s", value)
            end
            table.insert(lines, indent_[deps] .. "- " .. value)
        end
    else
        for key, value in pairs(t) do
            local typ = type(value)
            if typ == "table" then
                value, json_like = yaml_dump(value, deps + 1)
                if not json_like then
                    value = "\n" .. value
                end
            elseif typ == "string" then
                value = string.format(" %q", value)
            else
                value = string.format(" %s", value)
            end
            if not is_std_key(key) then
                --- key = "127.0.0.1:1980", 此时key需要加引号
                key = string.format("%q", key)
            end
            table.insert(lines, indent_[deps] .. key .. ":" .. value)
            if deps == 0 then
                table.insert(lines, "\n")
            end
        end
        if #lines == 0 then
            return getmetatable(t) == _M.array_mt and "[]" or "{}", true
        end
    end
    return table.concat(lines, "\n")
end

setmetatable(_M, {
    __call = function(_, lua_table)
        local yaml_str = yaml_dump(lua_table, 0)
        return yaml_str
    end })

return _M
